spring.application.name=infoyieldx
# === DATABASE CONFIG ===
spring.datasource.url=jdbc:mysql://localhost:3306/info
spring.datasource.username=root
spring.datasource.password=Akhila@14

# === JPA CONFIG ===

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#google.clientId=944679613259-6dj3p7mnr8v9qji346vvc95i7hsr8f3r.apps.googleusercontent.com


# === SERVER PORT (Optional) ===
server.port=8080
# For Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akhiy759@gmail.com
spring.mail.password=zzgm cbwo rnet tdho
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG



